### PR TITLE
Draft PR for Tag page

### PR DESCRIPTION
**Pull request by ericlp**
Still have to fix CSS and understand how to refresh props

### CODE REVIEW

**Comment by ericlp** [comment]
Will not work more on refreshing the props for now. The neat solution would be something like this https://github.com/vercel/next.js/discussions/12646 but I can't get it to work. The alternative solution would be to store tags using useState, but preferably not.

**Comment by ericlp** [comment]
Fixed the CSS for the page now, also changed opaque button to not look as ugly

**Comment by ericlp** [comment]
Fixed refresh props, I was stoop. Only thing left is to add method to add handle tags for recipes and recipebooks

**Review by ViddeM — APPROVED** [review]
👍🏿

**Pull request merged**
